export const CWPropertyDist = [
    {"owner": "PHILADELPHIA HOUSING AUTH", "property_count": 4009},
    {"owner": "NEIGHBORHOOD RESTORATIONS", "property_count": 556},
    {"owner": "MARINE CLUB ASSOCIATES LP", "property_count": 319},
    {"owner": "REDEVELOPMENT AUTHORITY O", "property_count": 189},
    {"owner": "SIENA PLACE PLANNED COMMU", "property_count": 129},
    {"owner": "COMMONWEALTH OF PENNSYLVA", "property_count": 128},
    {"owner": "VENICE LOFTS PROPERTY OWN", "property_count": 128},
    {"owner": "PHILADELPHIA REDEVELOPMEN", "property_count": 119},
    {"owner": "JAMISON ROAD ASSOCIATES L", "property_count": 110},
    {"owner": "FEDERAL NATIONAL MORTGAGE", "property_count": 107},
    {"owner": "KELLEY INVESTMENT GROUP L", "property_count": 75},
    {"owner": "LSF9 MASTER PARTICIPATION", "property_count": 75},
    {"owner": "PHILADELPHIA LAND INVESTM", "property_count": 64},
    {"owner": "PHILADELPHIA LOTUS 01A LL", "property_count": 62},
    {"owner": "GINARK INVESTMENT AND MAN", "property_count": 61},
    {"owner": "PHILADELPHIA LOTUS 03A LL", "property_count": 60},
    {"owner": "PHILADELPHIA LOTUS 02A LL", "property_count": 56},
    {"owner": "EQUITY TRUST COMPANY CUST", "property_count": 56},
    {"owner": "BELMONT AFFORDABLE HOUSIN", "property_count": 56},
    {"owner": "PHILADELPHIA LOTUS 08 LLC", "property_count": 55},
    {"owner": "LWCA NEW YORK INVESTORS L", "property_count": 55},
    {"owner": "TRUSTEES OF THE UNIVERSIT", "property_count": 54},
    {"owner": "CITY BLOCK ACQUISITION VI", "property_count": 52}
]