export const IWPropertyDist = [
  { owner: "PHILADELPHIA HOUSING AUTH", property_count: 343 },
  { owner: "CITY OF PHILA", property_count: 284 },
  { owner: "REDEVELOPMENT AUTHORITY", property_count: 190 },
  { owner: "PHILA HOUSING AUTHORITY", property_count: 134 },
  { owner: "TRS UNIV OF PENN", property_count: 102 },
  { owner: "PHILADELPHIA LAND BANK", property_count: 90 },
  { owner: "DREXEL UNIVERSITY", property_count: 82 },
  { owner: "PHILA REDEVELOPMENT AUTH", property_count: 65 },
  { owner: "BELMONT AFFORDABLE HOUSIN", property_count: 56 },
  { owner: "SIMON ASSOCIATES_LIMITED", property_count: 55 },
  { owner: "GEENA LLC", property_count: 47 },
  { owner: "TRUSTEES OF THE UNIVERSIT", property_count: 43 },
  { owner: "NEIGHBORHOOD RESTORATIONS", property_count: 42 },
  { owner: "CITY OF PHILADELPHIA", property_count: 39 },
  { owner: "SCHWARTZ SHELDON", property_count: 37 },
  { owner: "BROOKLYN HEIGHTS LP", property_count: 33 },
  { owner: "CAMPUS REALTY PROPERTIES", property_count: 32 },
  { owner: "STRONG PROPERTIES LLC", property_count: 31 },
  { owner: "WPRE II LP", property_count: 30 },
  { owner: "GILLER REALTY LLC", property_count: 26 },
  { owner: "AHM PROPERTIES LLC", property_count: 24 },
];
